{
 "title": "Employees Total 2",
 "tags": [ "P1" ],
 "time": { "from": "2026-03-16T14:59:15.629Z", "to": "2026-03-16T16:09:34.702Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Record insert total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  max(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\ngroup by date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Record insert / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  COUNT(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\nGROUP BY date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Record insert / minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  COUNT(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\nGROUP BY date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Totall count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT COUNT(id) FROM employees LIMIT 50 "
    }
   ]
  },
  {
   "title": "Record insert total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  max(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\ngroup by date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  }
 ]
}