{
 "title": "Employees Total",
 "tags": [ "P1" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Record insert total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  max(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\ngroup by date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Record insert / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  COUNT(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\nGROUP BY date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Departments",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT COUNT(department) AS \"value\", department AS \"Dep\" FROM employees GROUP BY department LIMIT 50 "
    }
   ]
  },
  {
   "title": "Totall count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT COUNT(id) FROM employees LIMIT 50 "
    }
   ]
  },
  {
   "title": "Salary statistics",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT MIN(salary) AS \"Min\", AVG(salary) AS \"Avg\", MAX(salary) AS \"Max\" FROM employees LIMIT 50 "
    }
   ]
  },
  {
   "title": "Record insert / minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  COUNT(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\nGROUP BY date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  },
  {
   "title": "Record insert total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "source_db",
     "rawSql": "SELECT\r\n  max(id) AS \"value\",\r\n  date_trunc('minute', created_at) AS \"time\"\r\nFROM employees\r\ngroup by date_trunc('minute', created_at)\r\nORDER BY \"time\";"
    }
   ]
  }
 ]
}