apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: airflow
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow
spec:
  serviceName: "airflow"
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: apache/airflow:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              airflow db init
              airflow users create \
                --username madmin \
                --password "$AIRFLOW_WWW_USER_PASSWORD" \
                --firstname Meyssam \
                --lastname Molaye \
                --role Admin \
                --email meyssam.molaye@gmail.com
              airflow standalone
          env:
            - name: AIRFLOW_WWW_USER_PASSWORD
              value: "hRM3ra4vHy9Uy78c" # Change this to your desired password
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW_CONN_POSTGRES_P1
              value: "postgresql://postgres@postgres-p1:5432/source_db"
            - name: AIRFLOW_CONN_POSTGRES_P2
              value: "postgresql://postgres@postgres-p2:5432/target_db"
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
            # CPU Optimization Settings
            - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
              value: "1" # Parse DAGs every 30s
            - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL
              value: "1" 
            - name: AIRFLOW__CORE__PARALLELISM
              value: "2"
            - name: AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG
              value: "1"
            - name: AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS
              value: "True"
            - name: AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE
              value: "europe/stockholm"
            - name: AIRFLOW__CORE__DEFAULT_TIMEZONE
              value: "europe/stockholm"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/v2/version
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 300
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags-volume
          hostPath:
            path: /home/development/deployment/airflow/dags
            type: Directory
