apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      containers:
        - name: node-exporter
          image: docker.io/prom/node-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  ports:
    - port: 9100
      targetPort: 9100
  selector:
    app: node-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: docker.io/percona/mongodb_exporter:0.50.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              value: "mongodb://mongos.mongo-sharding.svc.cluster.local:27017"
          ports:
            - containerPort: 9216
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
spec:
  ports:
    - port: 9216
      targetPort: 9216
  selector:
    app: mongodb-exporter
