apiVersion: v1
kind: Service
metadata:
  name: postgres-p2
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30434
  selector:
    app: postgres-p2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-p2
spec:
  serviceName: "postgres-p2"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-p2
  template:
    metadata:
      labels:
        app: postgres-p2
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "mkdir -p ~/deployment/postgresql/postgres-p2/data && chown -R 999:999 ~/deployment/postgresql/postgres-p2/data"]
          volumeMounts:
            - name: postgres-data
              mountPath: ~/deployment/postgresql/postgres-p2/data
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "p2password"
            - name: POSTGRES_DB
              value: "target_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: ~/deployment/postgresql/postgres-p2/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /home/development/deployment/postgresql/postgres-p2/data
            type: DirectoryOrCreate
