apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-p1-init
data:
  init.sql: |
    CREATE TABLE employees (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        department VARCHAR(100),
        salary NUMERIC,
        job_title VARCHAR(100),
        experience INTEGER,
        age INTEGER,
        education VARCHAR(100),
        city VARCHAR(100),
        tenure NUMERIC,
        skill_level VARCHAR(50),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-p1
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30433
  selector:
    app: postgres-p1
  clusterIP: 10.43.100.10
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-p1
spec:
  serviceName: "postgres-p1"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-p1
  template:
    metadata:
      labels:
        app: postgres-p1
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/data"]
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "p1password"
            - name: POSTGRES_DB
              value: "source_db"
            - name: PGDATA
              value: "/var/lib/postgresql/data"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-script
          configMap:
            name: postgres-p1-init
        - name: postgres-data
          hostPath:
            path: /home/development/deployment/postgresql/postgres-p1/data
            type: DirectoryOrCreate
