name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy manifests to server
        uses: appleboy/scp-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "kubernetes/*, scripts/*, airflow/dags/*"
          target: "~/deployment"

      - name: Setup Server
        uses: appleboy/ssh-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # script: |
          #   chmod +x ~/deployment/scripts/setup_server.sh
          #   ~/deployment/scripts/setup_server.sh

      - name: Apply Kubernetes manifests
        uses: appleboy/ssh-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🧹 Cleaning up existing resources..."
            # Delete non-default resources in the current namespace
            
            # Wait a moment for cleanup to finish
            sleep 5
            
            echo "🚀 Deploying new manifests..."
            cd ~/deployment/kubernetes
            export KUBECONFIG=/home/development/.kube/config
            ~/deployment/scripts/image_pull.sh
            kubectl get nodes
            # kubectl --insecure-skip-tls-verify=true delete deployments,services,pods,configmaps,pvc,statefulsets --all --ignore-not-found=true --force            
            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/postgres-p1.yaml
            echo "⏳ Waiting for Postgres-P1 to be ready..."
            kubectl --insecure-skip-tls-verify=true rollout status statefulset/postgres-p1 --timeout=120s

            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/postgres-p2.yaml
            echo "⏳ Waiting for Postgres-P2 to be ready..."
            kubectl --insecure-skip-tls-verify=true rollout status statefulset/postgres-p2 --timeout=120s

            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/airflow.yaml
            echo "⏳ Waiting for Airflow to be ready..."
            kubectl --insecure-skip-tls-verify=true rollout status statefulset/airflow --timeout=300s

            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/jenkins.yaml
            echo "⏳ Waiting for Jenkins to be ready..."
            kubectl --insecure-skip-tls-verify=true rollout status statefulset/jenkins --timeout=300s

            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/grafana.yaml
            echo "⏳ Waiting for Grafana to be ready..."
            kubectl --insecure-skip-tls-verify=true rollout status statefulset/grafana --timeout=120s

            echo "⏳ Applying monitoring exporters and integrations..."
            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/exporters.yaml
            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/prometheus.yaml

            kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/busybox.yaml
            echo "🚀 Waiting for Busybox to be ready..."
            kubectl --insecure-skip-tls-verify=true rollout status statefulset/busybox --timeout=120s
            # kubectl --insecure-skip-tls-verify=true apply -f ~/deployment/kubernetes/datadog.yaml || true
