name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy manifests to server
        uses: appleboy/scp-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "kubernetes/*, scripts/*, airflow/dags/*"
          target: "~/deployment"

      - name: Setup Server
        uses: appleboy/ssh-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          # script: |
          #   chmod +x ~/deployment/scripts/setup_server.sh
          #   ~/deployment/scripts/setup_server.sh

      - name: Apply Kubernetes manifests
        uses: appleboy/ssh-action@master
        with:
          host: home.meyssam.ir
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "🧹 Cleaning up unused resources..."
            kubectl delete -f ~/deployment/kubernetes/postgres-p1.yaml --ignore-not-found=true || true
            kubectl delete -f ~/deployment/kubernetes/postgres-p2.yaml --ignore-not-found=true || true
            kubectl delete -f ~/deployment/kubernetes/airflow.yaml --ignore-not-found=true || true
            kubectl delete -f ~/deployment/kubernetes/jenkins.yaml --ignore-not-found=true || true
            kubectl delete -f ~/deployment/kubernetes/spark.yaml --ignore-not-found=true || true
            
            echo "🚀 Deploying new manifests..."
            cd ~/deployment/kubernetes
            export KUBECONFIG=/home/development/.kube/config
            ~/deployment/scripts/image_pull.sh
            kubectl get nodes
            
            kubectl apply -f ~/deployment/kubernetes/mongodb.yaml
            echo "⏳ Waiting for MongoDB to be ready..."
            kubectl rollout status statefulset/mongodb --timeout=120s

            echo "🚀 Launching MongoDB Sharding Playground..."
            kubectl apply -f ~/deployment/kubernetes/mongo-sharding-practice.yaml

            kubectl apply -f ~/deployment/kubernetes/grafana.yaml
            echo "⏳ Waiting for Grafana..."
            kubectl rollout status statefulset/grafana --timeout=120s

            echo "⏳ Applying monitoring exporters and integrations..."
            kubectl apply -f ~/deployment/kubernetes/exporters.yaml
            kubectl apply -f ~/deployment/kubernetes/prometheus.yaml
            
            kubectl rollout status deployment/mongodb-exporter --timeout=120s
            kubectl rollout status statefulset/prometheus --timeout=120s

            kubectl apply -f ~/deployment/kubernetes/busybox.yaml
            echo "🚀 Waiting for Busybox to be ready..."
            kubectl rollout status statefulset/tools-pod --timeout=120s

